/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import controller.searchController;
import javax.swing.JOptionPane;
import static model.searchModel.*;

/**
 *
 * @author LENOVO
 */
public class searchView extends javax.swing.JFrame {

    /**
     * Creates new form searchView
     */
    public searchView() {
        initComponents();
        searchController obj=new searchController();
        if(obj.show()){
            datefield.setText(getDateVal());
            std.setText(getStdID());
            name.setText(getName1());
            phNum.setText(getNumber());
            email.setText(getEmail());
            fname.setText(getfName());
            mname.setText(getmName());
            address.setText(getAddress());
            college.setText(getCollege());
            room.setText(getRoom());
        }  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        std = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        college = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        phNum = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        datefield = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        printPanel.setBackground(new java.awt.Color(255, 255, 255));
        printPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Dormify - Hostel Management System");
        printPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 300, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("TechHive Hostel: The Accommodation Hub at Dillibazar Sadak");
        printPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 580, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Maitri Marg, Dillibazar, Kathmandu 44600");
        printPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        printPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 536, 10));

        jLabel1.setText("Date:");
        printPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 110, -1, -1));

        jLabel5.setText("Student ID:");
        printPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 110, 68, -1));

        jLabel6.setText("Name:");
        printPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 68, -1));

        jLabel8.setText("Email:");
        printPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 66, -1));

        jLabel9.setText("Father Name:");
        printPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 81, -1));

        jLabel10.setText("Mother Name:");
        printPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 81, -1));

        jLabel11.setText("Address: ");
        printPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 71, -1));

        jLabel12.setText("College:");
        printPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 71, -1));

        jLabel13.setText("Room no. :");
        printPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 71, -1));

        jLabel14.setText("Hostel Stamp");
        printPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 80, -1));
        printPanel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, -1));

        jLabel15.setText("______________________________");
        printPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        printPanel.add(std, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, -1));
        printPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, -1));
        printPanel.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 220, -1));
        printPanel.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 230, -1));
        printPanel.add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, -1));
        printPanel.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 200, -1));
        printPanel.add(phNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 200, -1));

        jLabel26.setText("Phone Number:");
        printPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));
        printPanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchbg.png"))); // NOI18N
        printPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel17.setText("______________________________");
        printPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jLabel18.setText("Signature");
        printPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 70, -1));
        printPanel.add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 90, -1));

        jButton1.setText("Save as Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save as PDF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BufferedImage image = new BufferedImage(printPanel.getWidth(), printPanel.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();
        printPanel.paint(g);
        g.dispose();
        
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath() + ".png";
            try {
                ImageIO.write(image, "png", new File(filePath));
                JOptionPane.showMessageDialog(null,"Image saved successfully.");
            } catch (IOException ex) {
                System.out.println("Error saving image: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);
                if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                printPanel.print(g2);               
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
                JOptionPane.showMessageDialog(null,"Pdf saved successfully.");
            }
            catch (PrinterException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel college;
    private javax.swing.JLabel datefield;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phNum;
    private javax.swing.JPanel printPanel;
    private javax.swing.JLabel room;
    private javax.swing.JLabel std;
    // End of variables declaration//GEN-END:variables
}
