/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projects;

import database.DbConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
            String email = loginDormify.getEnteredEmail();
            initComponents();
            try{
                Connection connect = DbConnection.connect();
                Statement statement = connect.createStatement();
                ResultSet result = statement.executeQuery("select * from signUp where email = '" + email + "'"); 
                if (result.next()) {
                    String fName = result.getString("fname");
                    String lName = result.getString("lname");
                    userName.setText("Hello "+fName + " " + lName+" !!");
                } else {
                    System.out.println("No matching records found for email: " + email);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        feature2 = new javax.swing.JButton();
        feature3 = new javax.swing.JButton();
        feature1 = new javax.swing.JButton();
        feature5 = new javax.swing.JButton();
        feature6 = new javax.swing.JButton();
        feature4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dormify-Dashboard");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1030, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, -1, -1));

        jButton7.setBackground(new java.awt.Color(102, 51, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        jButton7.setAutoscrolls(true);
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 40, 40));

        jButton8.setBackground(new java.awt.Color(102, 51, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 0, 40, 40));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 5, 329, 31));

        jButton10.setBackground(new java.awt.Color(102, 51, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton10.setText("Search");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 0, 93, 40));

        userName.setEditable(false);
        userName.setBackground(new java.awt.Color(102, 51, 255));
        userName.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        userName.setBorder(null);
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.getAccessibleContext().setAccessibleName("");

        feature2.setBackground(new java.awt.Color(217, 217, 217));
        feature2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature2.setText("Registration");
        feature2.setPreferredSize(new java.awt.Dimension(170, 50));
        feature2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature2ActionPerformed(evt);
            }
        });
        getContentPane().add(feature2, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 41, -1, -1));

        feature3.setBackground(new java.awt.Color(217, 217, 217));
        feature3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature3.setText("Update Details");
        feature3.setPreferredSize(new java.awt.Dimension(170, 50));
        feature3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature3ActionPerformed(evt);
            }
        });
        getContentPane().add(feature3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 41, -1, -1));

        feature1.setBackground(new java.awt.Color(217, 217, 217));
        feature1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature1.setText("Manage Rooms");
        feature1.setPreferredSize(new java.awt.Dimension(170, 50));
        feature1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature1ActionPerformed(evt);
            }
        });
        getContentPane().add(feature1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 41, -1, -1));

        feature5.setBackground(new java.awt.Color(217, 217, 217));
        feature5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature5.setText("Fees");
        feature5.setPreferredSize(new java.awt.Dimension(170, 50));
        feature5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature5ActionPerformed(evt);
            }
        });
        getContentPane().add(feature5, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 41, -1, -1));

        feature6.setBackground(new java.awt.Color(217, 217, 217));
        feature6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature6.setText("Status");
        feature6.setPreferredSize(new java.awt.Dimension(170, 50));
        feature6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature6ActionPerformed(evt);
            }
        });
        getContentPane().add(feature6, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 41, -1, -1));

        feature4.setBackground(new java.awt.Color(217, 217, 217));
        feature4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        feature4.setText("Attendance");
        feature4.setPreferredSize(new java.awt.Dimension(170, 50));
        feature4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feature4ActionPerformed(evt);
            }
        });
        getContentPane().add(feature4, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 41, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(1024, 4));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, -1, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
  
  
   
    private void feature6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature6ActionPerformed
        // TODO add your handling code here:
        feature6.setForeground(Color.black);
        feature6.setBackground(new Color(0,255,255));
        new statusBar().setVisible(true);
        feature1.setBackground(new Color(217,217,217));
        feature2.setBackground(new Color(217,217,217));
        feature3.setBackground(new Color(217,217,217));
        feature4.setBackground(new Color(217,217,217));
        feature5.setBackground(new Color(217,217,217));
    }//GEN-LAST:event_feature6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            setVisible(false);
            new loginDormify().setVisible(true);
        } else {
            //pass
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void feature1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature1ActionPerformed
        // TODO add your handling code here:
        feature1.setForeground(Color.black);
        feature1.setBackground(new Color(0,255,255));
        feature2.setBackground(new Color(217,217,217));
        feature3.setBackground(new Color(217,217,217));
        feature4.setBackground(new Color(217,217,217));
        feature5.setBackground(new Color(217,217,217));
        feature6.setBackground(new Color(217,217,217));
//        new manageRoom().setVisible(true); make file with this name undecorated
    }//GEN-LAST:event_feature1ActionPerformed

    private void feature2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature2ActionPerformed
        // TODO add your handling code here:
        feature2.setForeground(Color.black);
        feature2.setBackground(new Color(0,255,255));
        feature1.setBackground(new Color(217,217,217));
        feature3.setBackground(new Color(217,217,217));
        feature4.setBackground(new Color(217,217,217));
        feature5.setBackground(new Color(217,217,217));
        feature6.setBackground(new Color(217,217,217));
//        new registration().setVisible(true); make file with this name undecorated
    }//GEN-LAST:event_feature2ActionPerformed

    private void feature3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature3ActionPerformed
        // TODO add your handling code here:
        feature3.setForeground(Color.black);
        feature3.setBackground(new Color(0,255,255));
        feature1.setBackground(new Color(217,217,217));
        feature2.setBackground(new Color(217,217,217));
        feature4.setBackground(new Color(217,217,217));
        feature5.setBackground(new Color(217,217,217));
        feature6.setBackground(new Color(217,217,217));
//       new updateRegistration().setVisible(true); make file with this name undecorated
    }//GEN-LAST:event_feature3ActionPerformed

    private void feature4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature4ActionPerformed
        // TODO add your handling code here:
        feature4.setForeground(Color.black);
        feature4.setBackground(new Color(0,255,255));
        feature1.setBackground(new Color(217,217,217));
        feature2.setBackground(new Color(217,217,217));
        feature3.setBackground(new Color(217,217,217));
        feature5.setBackground(new Color(217,217,217));
        feature6.setBackground(new Color(217,217,217));
//      new attendance().setVisible(true); make file with this name undecorated

    }//GEN-LAST:event_feature4ActionPerformed

    private void feature5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feature5ActionPerformed
        // TODO add your handling code here:
        feature5.setForeground(Color.black);
        feature5.setBackground(new Color(0,255,255));
        feature1.setBackground(new Color(217,217,217));
        feature2.setBackground(new Color(217,217,217));
        feature3.setBackground(new Color(217,217,217));
        feature4.setBackground(new Color(217,217,217));
        feature6.setBackground(new Color(217,217,217));
//      new fees().setVisible(true); make file with this name undecorated

    }//GEN-LAST:event_feature5ActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String email = loginDormify.getEnteredEmail();
                if (email==null){
                    JOptionPane.showMessageDialog(null,"You cannot directly access Dashboard. Please Login first.");
                    new loginDormify().setVisible(true);
                }else{
                new dashboard().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feature1;
    private javax.swing.JButton feature2;
    private javax.swing.JButton feature3;
    private javax.swing.JButton feature4;
    private javax.swing.JButton feature5;
    private javax.swing.JButton feature6;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
